### ISSUE TITLE
Security issue as no more real chroot

### ISSUE THREAD

**Issue by joknarf** [mysecureshell/mysecureshell#14]
Since no real chroot done anymore (since:  Déplacement de la gestion du file system dans les functions FS\* )

Symlinks pointing outside the VirtualChroot provide access to directories/files outside the cage

I won't use any new version anymore without chroot ... :-(

**Comment by GeoffreyFrogeye** [comment]
Can't we at least add an option to not follow symbolic links at all?
Because for now if you can write symlinks you can basically override any `FileSpec` or `StayAtHome` tag.
You can use `DisableSymLink` but this does not prevent from existing or third-party created symlinks.

I also find the lack of documentation for this security issue kinda concerning. Mind if I open a PR to add some for the tags that can be overridden?

**Comment by Teka101** [comment]
Hi,

If you want to lock an user in this home, you can use [VirtualChroot](https://mysecureshell.readthedocs.io/en/latest/tags/childs/virtualchroot.html)

For any suggestions create a PR please

**Comment by GeoffreyFrogeye** [comment]
VirtualChroot does not prevent this exploit. If you have a symlink to / inside the chroot, the user can access the whole filesystem.

I will create a PR, I just wanted to know if you were OK with that before putting any work into it.

**Comment by Teka101** [comment]
Mhhhhhh right.

Maybe only with StayAtHome should be ok ? ...

**Comment by SvenMW** [comment]
Hi and no offense, but do you really find it responsible to advertise this as a "secure shell" when it contains such glaring security holes? @Teka101 

As far as I can see it is not mentioned at least in the docs, that the "chroot" feature does not work as advertised?
